services:
  rabbitmq:
    image: rabbitmq:4.1.2-alpine
    restart: always
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq

  api:
    ports:
      - "8000:8000"
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    restart: always
    environment:
      - SERVER_PORT=8000

      - RABBIT_PORT=5672
      - RABBIT_HOST=rabbitmq
      - RABBIT_USER=user
      - RABBIT_PASSWORD=password

      - DETECT_IMAGE_TIMEOUT=20

  detector:
    build:
      context: ./detector
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - api
    restart: always
    environment:
      - RABBIT_PORT=5672
      - RABBIT_HOST=rabbitmq
      - RABBIT_USER=user
      - RABBIT_PASSWORD=password