name: Deploy

on:
  push:
    branches:
      - workflow-test

jobs:
  build-and-copy:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci
        working-directory: additional/frontend

      - name: Build frontend
        run: npm run build
        working-directory: additional/frontend
      
      - name: Create secrets.env file
        run: |
          echo "RABBIT_USER=${{ secrets.RABBIT_USER }}" >> secrets.env
          echo "RABBITMQ_DEFAULT_USER=${{ secrets.RABBIT_USER }}" >> secrets.env

          echo "RABBIT_PASSWORD=${{ secrets.RABBIT_PASSWORD }}" >> secrets.env
          echo "RABBITMQ_DEFAULT_PASS=${{ secrets.RABBIT_PASSWORD }}" >> secrets.env
      
      - name: Create api.env file
        run: |
          echo "API_NAME=${{ vars.API_NAME }}" >> api.env
          echo "DOCS_PREFIX=${{ vars.API_DOCS_PREFIX }}" >> api.env
          echo "DETECT_IMAGE_TIMEOUT=${{ vars.API_DETECT_IMAGE_TIMEOUT }}" >> api.env
      
      - name: Prepare deploy directory
        run: |
          mkdir -p deploy/frontend
          cp -r additional/frontend/dist/* deploy/frontend/
          cp -r services deploy/
          cp docker-compose.yaml deploy/
          cp api.env deploy/
          cp secrets.env deploy/
      
      - name: Archive deploy directory
        run: |
          cd deploy
          zip -r ../deploy.zip . -x '*.git*' '*.github/*'
      
      - name: Transfer files to server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          source: "deploy.zip"
          target: "/home/${{ secrets.SERVER_USER }}/AIImageDetector/"
  
  run-services:
    runs-on: ubuntu-latest
    needs: build-and-copy
    steps:
      - name: Run services
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            cd /home/${{ secrets.SERVER_USER }}/AIImageDetector/
            unzip -o deploy.zip
            wget -O services/detector/model.pt https://huggingface.co/ycalk/AIImageDetector/resolve/main/model.pt
            docker compose build
            docker compose down
            docker compose up -d --remove-orphans
            docker image prune -f
            rm deploy.zip