name: Tests

on:
  push:
    branches: 
      - main

jobs:
  test-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./services/api
    env:
      RABBIT_PASSWORD: guest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir poetry==2.1.3
          poetry install --with dev

      - name: Run tests
        run: |
          poetry run pytest --disable-warnings -v